# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\password.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QMessageBox
import random

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(849, 728)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 250, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 330, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 400, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(90, 480, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(242, 260, 201, 31))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(60, 30, 821, 151))
        self.frame.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"background-color: rgb(27, 21, 21);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(60, 30, 711, 91))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.label_5.setObjectName("label_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(240, 340, 201, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(240, 410, 201, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(240, 490, 201, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 580, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(490, 250, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(490, 320, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(640, 260, 201, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(640, 330, 201, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(480, 370, 450, 142))
        self.textEdit.setObjectName("textEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(480, 540, 160, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(460, 260, 16, 401))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(463, 260, 20, 391))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 849, 21))
        self.menubar.setObjectName("menubar")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(670, 540, 160, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.pushButton.clicked.connect(self.submit)
        self.pushButton_2.clicked.connect(self.search)
        self.pushButton_3.clicked.connect(self.fetchAll)
        self.statusbar.setObjectName("statusbar")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_6.setEchoMode(QtWidgets.QLineEdit.Password)
        MainWindow.setStatusBar(self.statusbar)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def submit(self):
        print("(!) DEBUG: Clicked Submit Btn")

        user = self.lineEdit.text()

        passc = self.lineEdit_2.text()

        web = self.lineEdit_3.text()

        key = self.lineEdit_4.text()

        print(f"(!) DEBUG:"
              f"user: {user} \n"
              f"passc: {passc} \n"
              f"web: {web} \n"
              f"fkey: {key} \n")
        
        isNumber = False
        isUpperCase = False
        isLowerCase = False
        isSpecialChar = False
        isEnoughLen = len(passc)>=8
        special_characters = "!@#$%^&*()?/"
        for i in range(len(passc)):
            c = passc[i]

            if c.isdigit():
                isNumber = True     
            elif c.isupper():
                isUpperCase = True
            elif c.islower():
                isLowerCase = True
            elif c in special_characters:
                isSpecialChar = True

        if isNumber == True and isUpperCase == True and isLowerCase == True and isSpecialChar == True and isEnoughLen == True:
            msgBox = QMessageBox()
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setText("Entry Successful added in Database")
            msgBox.setWindowTitle("Simple Pass Manager")
            msgBox.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)

            returnValue = msgBox.exec()

            conn = sqlite3.connect('password.sqlite')
            cur = conn.cursor()

            task = (user,passc,web,key)
            cur.execute('INSERT INTO pass (user,pass,web,key) values (?,?,?,?)',task)

            conn.commit()
            conn.close()

    def search(self):
        print("(!) DEBUG: Clicked Search Btn")

        keyword = self.lineEdit_6.text()

        website = self.lineEdit_5.text()

        print(f"(!) DEBUG:"
              f"keyword: {keyword} \n"
              f"website: {website} \n")
        
        if(keyword != ""):
            conn = sqlite3.connect('password.sqlite')
            cur = conn.cursor()
            cur.execute("SELECT * from pass WHERE key=?",[keyword])
            rows = cur.fetchall()
            formatted_text = "Website \t Username \t Password \t Key \n ------ \t ------ \t ------ \t ------ \n"
            for row in rows:
                print(row)
                formatted_text += f"{row[2]} \t {row[0]} \t {row[1]} \t {row[3]}\n"
            self.textEdit.setText(formatted_text)
            conn.commit()
            conn.close()
        else:
            self.textEdit.setText("Access Code is invalid")
            msgBox = QMessageBox()
            msgBox.setIcon(QMessageBox.Critical)
            msgBox.setWindowTitle("SIMPLE PASS MANAGER")
            msgBox.setText("Wrong Access Code, Please try again!!")
            msgBox.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)

    def fetchAll(self):
        print("(!) DEBUG: Clicked Fetch All Btn")

        
        conn = sqlite3.connect('password.sqlite')
        cur = conn.cursor()
        cur.execute("SELECT * from pass")
        rows = cur.fetchall()
        formatted_text = "Website \t Username \t Password \t Key \n ------ \t ------ \t ------ \t ------ \n"
        for row in rows:
            print(row)
            formatted_text += f"{row[2]} \t {row[0]} \t {row[1]} \t {row[3]}\n"
        self.textEdit.setText(formatted_text)
        conn.commit()
        conn.close()
    


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Username"))
        self.label_2.setText(_translate("MainWindow", "Password"))
        self.label_3.setText(_translate("MainWindow", "Website"))
        self.label_4.setText(_translate("MainWindow", "Access Code"))
        self.label_5.setText(_translate("MainWindow", "  SIMPLE PASS MANAGER"))
        self.pushButton.setText(_translate("MainWindow", "Submit "))
        self.label_6.setText(_translate("MainWindow", "Website"))
        self.label_7.setText(_translate("MainWindow", "Access Code"))
        self.pushButton_2.setText(_translate("MainWindow", "Search"))
        self.pushButton_3.setText(_translate("MainWindow", "Fetch All"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
